<?php /* @var $this Hps_Transit_Block_Form */
$_code = $this->getMethodCode();
$_loggedIn = Mage::getSingleton('customer/session')->isLoggedIn();
$token_data_url = Mage::getUrl('transit/storedcard/getTokenData', array('_secure' => TRUE));
$allow_card_saving = Mage::getModel('hps_transit/payment')->getConfigData('allow_card_saving');
$use_iframes = true;

if ($_loggedIn && $allow_card_saving) {
    $customerStoredCards = Mage::helper('hps_transit')->getStoredCards( Mage::getSingleton('customer/session')->getCustomerId());
}
?>

<ul class="form-list" id="payment_form_<?= $_code ?>" style="display:none;">

    <li id="ss-banner" style="border:none;"></li>

    <!-- START SAVED CREDIT CARD LIST -->
    <?php if($_loggedIn && $allow_card_saving && isset($customerStoredCards) && count($customerStoredCards)): ?>
        <?php $checked = true; ?>
        <?php foreach ($customerStoredCards as $key => $card): ?>
          <li<?php if ($checked): ?> class="active"<?php endif ?>>
            <label for="<?= $_code ?>_stored_card_select_<?= $card->getId() ?>" class="<?= $_code ?>_stored_card_label">
                    <div class="saved-card-selector <?php if ($checked): ?>selected<?php endif ?>">
                        <input type="radio" name="<?= $_code ?>_stored_card_select" id="<?= $_code ?>_stored_card_select_<?= $card->getId() ?>" value="<?= $card->getId() ?>" <?php if ($checked): ?>checked="checked"<?php $checked=false; endif ?>/>
                    </div>
                    <div class="cc-info">
                        <input type="hidden" id="<?= $_code ?>_stored_card_select_<?= $card->getId() ?>_card_type" value="<?= $card->getCcType() ?>" />
                        <span class="cc" style="float:left"><?= $card->getCcType().' ....'.$card->getCcLast4()?></span><br>
                        <span class="exp"><?= "expires on" ." "  .' (' .$card->getCcExpMonth().'/'.$card->getCcExpYear().')' ?></span>
                    </div>
                    <div id="stored-cc-icon" class="icon-<?= strtolower($card->getCcType()) ?>-form"></div>
            </label>
          </li>
        <?php endforeach ?>

        <li style="display:none">
            <input type="hidden" id="<?= $_code ?>_use_stored_card" name="payment[cc_use_multi]">
        </li>
    <?php endif ?>

    <!-- START NEW CARD -->
    <?php $checked = !$_loggedIn || !(isset($customerStoredCards) && count($customerStoredCards));?>
    <li id="new-card-section">
        <?php if (!$checked): ?>
            <label for="<?= $_code ?>_stored_card_select_new" class="<?= $_code ?>_stored_card_label" style="padding:0px 0px;">
                <div class="cc-option">
                    <div class="saved-card-selector">
                        <input type="radio" name="<?= $_code ?>_stored_card_select" id="<?= $_code ?>_stored_card_select_new" value="new" />
                    </div>
                    <p><?= $this->__('Pay with a new credit card') ?></p>
                </div>
            </label>
        <?php else: ?>
            <input type="radio" name="<?= $_code ?>_stored_card_select" id="<?= $_code ?>_stored_card_select_new" value="new" checked="checked" style="display:none;"/>
        <?php endif ?>
        <div id="<?= $_code ?>_cc_form" <?php if (!$checked): ?>style="display: none;"<?php endif ?>>
            <div id="cc-number">
                <label for="<?= $_code ?>_cc_number"><?= $this->__('Credit Card Number') ?> <span class="required">&nbsp;</span></label>
                <div id="<?= $_code ?>_cc_number_iframe"></div>
                <input type="hidden" id="<?= $_code ?>_token" name="payment[transit_token]">
                <input type="hidden" id="<?= $_code ?>_cc_last_four" name="payment[cc_last_four]">
                <input type="hidden" id="<?= $_code ?>_cc_type" name="payment[cc_type]">
                <input type="hidden" id="<?= $_code ?>_cc_cid" name="payment[cc_cid]">
            </div>


            <div id="expiration-date">
                <label for="<?= $_code ?>_expiration"><?= $this->__('Expiration Date') ?> <span class="required">&nbsp;</span></label>
                <div id="<?= $_code ?>_cc_exp_iframe"></div>
                <input type="hidden" id="<?= $_code ?>_cc_exp_month" name="payment[cc_exp_month]">
                <input type="hidden" id="<?= $_code ?>_cc_exp_year" name="payment[cc_exp_year]">
            </div>

            <div id="ccv">
                <label for="<?= $_code ?>_cvv_number"><?= $this->__('Card Verification Number') ?> <span class="required">&nbsp;</span></label>
                <div id="<?= $_code ?>_cc_cvv_iframe"></div>
            </div>

            <?php if ($_loggedIn && $allow_card_saving): ?>
                <div class="save-card-checkbox">
                    <input type="checkbox" id="<?= $_code ?>_cc_save_future" name="payment[cc_save_future]" value="Y" autocomplete="off" />
                    <label id="ss-save-text" for="<?= $_code ?>_cc_save_future"><?= $this->__('&nbsp; &nbsp;Save this card for future use?') ?></label>
                </div>
            <?php endif ?>
        </div>
    </li>
</ul>

<script type="text/javascript">
//<![CDATA[
TransITMagento.init({
    code: '<?= $_code ?>',
    baseUrl: '<?= Mage::getBaseUrl() ?>',
    loggedIn: <?= $_loggedIn ? 'true' : 'false' ?>,
    credentials: <?= $this->getCredentials() ?>,
    allowCardSaving: <?= $allow_card_saving ? 'true' : 'false' ?>,
    tokenDataUrl: '<?= $token_data_url ?>',
    allowGift: false,
    useIframes: true,
    iframeTargets: {
        cardNumber: '#<?= $_code ?>_cc_number_iframe',
        cardExpiration: '#<?= $_code ?>_cc_exp_iframe',
        cardCvv: '#<?= $_code ?>_cc_cvv_iframe'
    }
});

<?php if ($_loggedIn && $allow_card_saving && count($customerStoredCards)): ?>
$$('.saved-card-selector input').each(function(element){
    element.addEventListener('click', function(e) {
        $$('.saved-card-selector').each(function(element){
            element.removeClassName('selected');
        });
        e.srcElement.parentNode.addClassName('selected');
    });
});
<?php endif ?>

if ((typeof iwdOpcConfig !== 'undefined') && (typeof OnePage !== 'undefined') && (typeof PaymentMethod !== 'undefined')) {
    $ji('ul#payment_form_<?= $_code ?>').css('display','block');
    // Remove the `required-entry` class from the input fields to prevent IWD Checkotu Suite
    // from validating the fields before the consumer has a chance to even enter data
    $ji('#payment_form_<?= $_code ?> .required-entry').removeClass('required-entry');
}
//]]>
</script>
