<?php /** @var $this Hps_Transit_Block_Adminhtml_Form */
$_code = $this->getMethodCode();
$store = Mage::getSingleton('adminhtml/session_quote')->getStore();
$storeId = ($store) ? $store->getId() : NULL;
$customerStoredCards = $this->getCustomerStoredCards();
$useStoredCard = (bool) $this->getInfoData('transit_use_stored_card');
$customerId = Mage::getSingleton('adminhtml/session_quote')->getCustomerId();
$allow_card_saving = Mage::getModel('hps_transit/payment')->getConfigData('allow_card_saving', $storeId);
?>

<input id="<?php echo $_code ?>_payment_method" type="hidden" name="payment[method]" value="<?php echo $_code ?>" />
<ul id="payment_form_<?php echo $_code ?>" class="form-list" style="display:none;">
    <?php if($allow_card_saving && count($customerStoredCards)): ?>
        <li>
            <label for="<?php echo $_code ?>_stored_card_checkbox"><?php echo $this->__('Use a stored card') ?></label>
            <div class="input-box">
                <input type="checkbox" id="<?php echo $_code ?>_stored_card_checkbox" name="payment[transit_use_stored_card]" <?php if ($useStoredCard) : ?> checked="checked" <?php endif ?> value="1" />
            </div>
        </li>
        <li id="<?php echo $_code ?>_stored_cards" style="display: none">
            <label for="<?php echo $_code ?>_stored_card_select"><?php echo $this->__('Stored Card') ?></label>
            <div class="input-box">
                <select id="<?php echo $_code ?>_stored_card_select"  autocomplete="off">
                    <?php foreach ($customerStoredCards as $key => $card): ?>
                        <option value="<?php echo $card->getId() ?>"><?php echo $card->getCcType().' ************'.$card->getCcLast4().' ('.$card->getCcExpMonth().'/'.$card->getCcExpYear().')' ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </li>
    <?php endif ?>

    <li class="stored_cards_selected">
        <label for="<?= $_code ?>_cc_number"><?= $this->__('Credit Card Number') ?> <span class="required">&nbsp;</span></label>
        <div id="<?= $_code ?>_cc_number_iframe"></div>
        <input type="hidden" id="<?= $_code ?>_token" name="payment[transit_token]">
        <input type="hidden" id="<?= $_code ?>_cc_last_four" name="payment[cc_last_four]">
        <input type="hidden" id="<?= $_code ?>_cc_type" name="payment[cc_type]">
        <input type="hidden" id="<?= $_code ?>_cc_cid" name="payment[cc_cid]">
    </li>


    <li class="stored_cards_selected">
        <label for="<?= $_code ?>_expiration"><?= $this->__('Expiration Date') ?> <span class="required">&nbsp;</span></label>
        <div id="<?= $_code ?>_cc_exp_iframe"></div>
        <input type="hidden" id="<?= $_code ?>_cc_exp_month" name="payment[cc_exp_month]">
        <input type="hidden" id="<?= $_code ?>_cc_exp_year" name="payment[cc_exp_year]">
    </li>

    <li class="stored_cards_selected">
        <label for="<?= $_code ?>_cvv_number"><?= $this->__('Card Verification Number') ?> <span class="required">&nbsp;</span></label>
        <div id="<?= $_code ?>_cc_cvv_iframe"></div>
    </li>

    <?php if ($allow_card_saving): ?>
        <li class="stored_cards_selected">
            <label for="<?php echo $_code ?>_cc_save_future"><?php echo $this->__('Save this card for future use?') ?></label>
            <div class="input-box">
                <input type="checkbox" id="<?php echo $_code ?>_cc_save_future" name="payment[cc_save_future]" value="Y" autocomplete="off" />
                <input type="hidden" id="<?php echo $_code ?>_customer_id" name="payment[customer_id]" value="<?php echo $customerId; ?>" />
            </div>
        </li>
    <?php endif ?>
</ul>
<script type="text/javascript">
//<![CDATA[
(function () {
    <?php if (count($customerStoredCards)) : ?>
        order.customerStoredCards = <?php echo json_encode($this->getJsConfig()) ?>;
        var storedCardCheckbox = $('<?php echo $_code ?>_stored_card_checkbox');
        storedCardCheckbox.stopObserving('click').observe('click', toggleStoredCards);
        function toggleStoredCards() {
            // Toggle between the saved credit cards and a new card form
            $$('.stored_cards_selected').invoke('toggle');
            $('<?php echo $_code ?>_stored_cards').toggle();
            var useStoredCard = $('<?php echo $_code ?>_use_credit_card');
            if (useStoredCard) {
                useStoredCard.value = storedCardCheckbox && storedCardCheckbox.checked ? '0' : '1';
            }
        }
        <?php if ($useStoredCard) : ?>
            toggleStoredCards();
        <?php endif ?>
    <?php endif ?>

    window.TransITMagentoAdmin = window.TransITMagentoAdmin || {};
    window.TransITMagentoAdmin.options = {
        code: '<?= $_code ?>',
        credentials: <?= $this->getCredentials() ?>,
        baseUrl: '<?= Mage::getBaseUrl() ?>',
        tokenDataUrl: '<?php echo Mage::getUrl('transit/storedcard/getTokenData', array('_secure' => TRUE)) ?>',
        iframeTargets: {
            cardNumber: '#<?= $_code ?>_cc_number_iframe',
            cardExpiration: '#<?= $_code ?>_cc_exp_iframe',
            cardCvv: '#<?= $_code ?>_cc_cvv_iframe'
        }
    };

    if (window.TransITMagentoAdmin.setupFields) {
        window.TransITMagentoAdmin.loadLibrary(window.TransITMagentoAdmin.setupFields);
    }
})();
//]]>
</script>
